-- 1. Create Channels Table for Force Subscribe if not exists
CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    invite_link TEXT NOT NULL,
    creates_join_request BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Alter Users table to add new columns if they do not exist (Non-destructive)
ALTER TABLE users ADD COLUMN IF NOT EXISTS wallet TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_exists BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS username_entropy DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cheat_score DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_bonus_claim TIMESTAMP WITH TIME ZONE;

-- 3. Create Withdrawals Table if not exists
-- References users(telegram_id) matching the existing column name
CREATE TABLE IF NOT EXISTS withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE NOT NULL,
    wallet TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Settings Table if not exists
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 5. Insert Default Settings if they do not exist
INSERT INTO settings (key, value) VALUES
('contest_active', 'true'),
('min_withdrawal_points', '5'),
('points_per_referral', '1'),
('daily_bonus_points', '1')
ON CONFLICT (key) DO NOTHING;

-- 6. Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 7. Drop existing policies if they exist, then recreate
DROP POLICY IF EXISTS "Allow public read users" ON users;
DROP POLICY IF EXISTS "Allow public insert users" ON users;
DROP POLICY IF EXISTS "Allow public update users" ON users;
DROP POLICY IF EXISTS "Allow public read channels" ON channels;
DROP POLICY IF EXISTS "Allow admin update channels" ON channels;
DROP POLICY IF EXISTS "Allow public insert withdrawals" ON withdrawals;
DROP POLICY IF EXISTS "Allow public read withdrawals" ON withdrawals;
DROP POLICY IF EXISTS "Allow public update withdrawals" ON withdrawals;
DROP POLICY IF EXISTS "Allow public read settings" ON settings;

-- 8. Users Policies
CREATE POLICY "Allow public read users" ON users FOR SELECT USING (true);
CREATE POLICY "Allow public insert users" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update users" ON users FOR UPDATE USING (true) WITH CHECK (true);

-- 9. Channels Policies
CREATE POLICY "Allow public read channels" ON channels FOR SELECT USING (true);
CREATE POLICY "Allow admin update channels" ON channels FOR ALL USING (true);

-- 10. Withdrawals Policies
CREATE POLICY "Allow public insert withdrawals" ON withdrawals FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read withdrawals" ON withdrawals FOR SELECT USING (true);
CREATE POLICY "Allow public update withdrawals" ON withdrawals FOR UPDATE USING (true);

-- 11. Settings Policies
CREATE POLICY "Allow public read settings" ON settings FOR SELECT USING (true);

-- 12. Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by);
CREATE INDEX IF NOT EXISTS idx_users_points ON users(points DESC);
CREATE INDEX IF NOT EXISTS idx_withdrawals_tg_id ON withdrawals(tg_id);
CREATE INDEX IF NOT EXISTS idx_users_is_banned ON users(is_banned);
